version: "3.8"

services:
  config-server:
    build: ./config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=native

  eureka-server:
    build: ./eureka_server
    ports:
      - "8084:8084"
    depends_on:
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=default

  gateway:
    build: ./gateway
    ports:
      - "5001:5001"
    depends_on:
      - config-server
      - eureka-server
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=default

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=default

  task-service:
    build: ./task-service
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=default

  submission-service:
    build: ./submission-service
    ports:
      - "8083:8083"
    depends_on:
      - config-server
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=default

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes


  zipkin:
    container_name: task_manager_zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:

volumes:
  redis_data:
